" ---------------------- USABILITY CONFIGURATION ----------------------
"  Basic and pretty much needed settings to provide a solid base for
"  source code editing

" Don't make vim compatible with vi
set nocompatible

" Turn on syntax highlighting
syntax on

" Highlight current line
set cursorline


" Make vim try to detect file types and load plugins for them
filetype on
filetype plugin on
filetype indent on

" Reload files changed outside vim
set autoread

" Encoding
set encoding=utf-8
set fileencoding=utf-8

" Enable matchit plugin which ships with vim and greatly enhances '%'
runtime macros/matchit.vim

" By default, in insert mode backspace won't delete over line breaks, or
" automatically-inserted indentation, let's change that
set backspace=indent,eol,start

" Don't unload buffers when they are abandoned, instead stay in the background
set hidden

" Set unix line endings
set fileformat=unix

" When reading files try unix line endings then dos, also use unix for new buffers
set fileformats=unix,dos

" ---------------------- CUSTOMIZATION ----------------------
"  The following are some extra mappings/configs to enhance my personal
"  VIM experience

" Set , as mapleader
let mapleader = ","

" Hide unnecessary gui in gVim
if has("gui_running")
    set guioptions-=m  " remove menu bar
    set guioptions-=T  " remove toolbar
    set guioptions-=r  " remove right-hand scroll bar
    set guioptions-=L  " remove left-hand scroll bar
end

" Indentation
set expandtab       " Use spaces instead of tabs
set autoindent      " Autoindent based on line above, works most of the time
set smartindent     " Smarter indent for C-like languages
set shiftwidth=2    " When reading, tabs are 4 spaces
set softtabstop=2   " In insert mode, tabs are 4 spaces

" On file types...
"   .md files are markdown files
autocmd BufNewFile,BufRead *.md setlocal ft=markdown


" Start NERDTree on start-up and focus active window
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

" Map FuzzyFinder
noremap <leader>b :FufBuffer<cr>
noremap <leader>f :FufFile<cr>

" Line Numbers
set number relativenumber
" High line numbers
highlight LineNr ctermfg=grey
