[tools]
node = "lts"
ruby = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[env]
SSL_CERT_FILE = "/opt/homebrew/etc/ca-certificates/cert.pem"
PORTABLE_RUBY_SSL_CERT_FILE = "/opt/homebrew/etc/ca-certificates/cert.pem"
